### ISSUE TITLE
pcluster not found on Cloud 9 workspace

### ISSUE THREAD

**Issue by rsignell-usgs** [aws-samples/no-tears-cluster#5]
When I launch the stack and connect to the Cloud 9 workspace, pcluster is not there:
```
rsignell:~/environment $ more Welcome.txt 
  _   _         _______                     _____ _           _
 | \ | |       |__   __|                   / ____| |         | |
 |  \| | ___      | | ___  __ _ _ __ ___  | |    | |_   _ ___| |_ ___ _ __
 | . ` |/ _ \     | |/ _ \/ _` | '__/ __| | |    | | | | / __| __/ _ \ '__|
 | |\  | (_) |    | |  __/ (_| | |  \__ \ | |____| | |_| \__ \ ||  __/ |
 |_| \_|\___/     |_|\___|\__,_|_|  |___/  \_____|_|\__,_|___/\__\___|_|

 To get started, run:

 $ pcluster list --color

 To ssh into the cluster, once it's gone into CREATE_COMPLETE, run:

 $ pcluster ssh hpc-cluster

 To connect to the desktop GUI via DCV run:

 $ pcluster dcv connect hpc-cluster
```
```
rsignell:~/environment $ pcluster list --color
Traceback (most recent call last):
  File "/usr/bin/pcluster", line 33, in <module>
    sys.exit(load_entry_point('aws-parallelcluster==2.8.0', 'console_scripts', 'pcluster')())
  File "/usr/bin/pcluster", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for aws-parallelcluster
rsignell:~/environment $ 
```
It seemed from the [no tears video](https://intel-hpc-ai-pavilion.gallery.video/detail/videos/hpc/video/6165858560001/no-tears-hpc-cluster-in-the-cloud?autoStart=true) that pcluster would already be installed.

I tried installing pcluster (using conda), but then I get:
```
(aws) rsignell:~/environment $ pcluster list --color
ERROR: Error when calling DescribeInstanceTypes for instances c5.2xlarge: Request has expired.
```
@sean-smith I hope this provides enough clues what I'm not doing correctly...

**Comment by sean-smith** [comment]
@rsignell-usgs Taking a look

**Comment by sean-smith** [comment]
@rsignell-usgs Can you run a few commands for me? The line that's breaking is https://github.com/aws-samples/no-tears-cluster/blob/release/scripts/bootstrap.sh#L31 which I assume has to due with how Cloud9 manages aws credentials (my guess would be that Cloud9 changed something about their credential management in multi-user environment). 

To start can you run:

```bash
sudo pip-3.6 --disable-pip-version-check --no-cache-dir install aws-parallelcluster==2.8.0 --upgrade

```

Did you specify a pcluster version in the cloudformation stack?

**Comment by sean-smith** [comment]
Ok I was able to reproduce, disregard my previous comment. I'll figure out what's breaking

**Comment by sean-smith** [comment]
Ok when I run:

```bash
$ sudo pip-3.6 --disable-pip-version-check --no-cache-dir install aws-parallelcluster==2.8.0 --upgrade
...
$ pcluster list --color
Traceback (most recent call last):
  File "/usr/bin/pcluster", line 33, in <module>
    sys.exit(load_entry_point('aws-parallelcluster==2.8.1', 'console_scripts', 'pcluster')())
  File "/usr/bin/pcluster", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for aws-parallelcluster
```

Looks like it's an issue with pip in the virtual env. 

https://stackoverflow.com/questions/54552367/pip-cannot-find-metadata-file-environmenterror

**Comment by sean-smith** [comment]
Hmm so I got it working with `pip3` instead of `pip-3.6`

**Comment by rsignell-usgs** [comment]
@sean-smith, I'm guessing you didn't mean that I just need to install `pcluster` using pip3, right?   
For me, that produced the same "no package metadata" error: 
```
       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/
No packages needed for security; 4 packages available
Run "sudo yum update" to apply all updates.
```
```
AWS-HPC-Quickstart-ResearcherB0ACBDEC-1058NFFMNDDPU:~/environment $ pcluster
Traceback (most recent call last):
  File "/usr/bin/pcluster", line 33, in <module>
    sys.exit(load_entry_point('aws-parallelcluster==2.8.0', 'console_scripts', 'pcluster')())
  File "/usr/bin/pcluster", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__sudo pip-3.6 --disable-pip-version-check --no-cache-dir install aws-parallelcluster==2.8.0 --upgrade
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for aws-parallelcluster
```
```
AWS-HPC-Quickstart-ResearcherB0ACBDEC-1058NFFMNDDPU:~/environment $ sudo pip3 --disable-pip-version-check --no-cache-dir install aws-parallelcluster==2.8.0 --upgrade                                        
Collecting aws-parallelcluster==2.8.0
  Downloading https://files.pythonhosted.org/packages/fb/06/46f3d1717920d7a77db753c6e0fa055fb4a484fab7c8d06a9340576871bb/aws-parallelcluster-2.8.0.tar.gz (110kB)
    100% |████████████████████████████████| 112kB 4.2MB/s 
/usr/local/lib/python3.6/site-packages/_distutils_hack/__init__.py:19: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  "Distutils was imported before Setuptools, but importing Setuptools "
/usr/local/lib/python3.6/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Requirement already up-to-date: setuptools in /usr/local/lib/python3.6/site-packages (from aws-parallelcluster==2.8.0)
Collecting boto3>=1.14.3 (from aws-parallelcluster==2.8.0)
  Downloading https://files.pythonhosted.org/packages/26/48/40dbd811d4131fc3076b0ee0b4b6f86352fdfc2d5fe824213521d5164223/boto3-1.14.53.tar.gz (97kB)
    100% |████████████████████████████████| 102kB 15.7MB/s 
Collecting future<=0.18.2,>=0.16.0 (from aws-parallelcluster==2.8.0)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 20.9MB/s 
Collecting tabulate<=0.8.3,>=0.8.2 (from aws-parallelcluster==2.8.0)
  Downloading https://files.pythonhosted.org/packages/c2/fd/202954b3f0eb896c53b7b6f07390851b1fd2ca84aa95880d7ae4f434c4ac/tabulate-0.8.3.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 28.0MB/s 
Requirement already up-to-date: ipaddress>=1.0.22 in /usr/local/lib/python3.6/site-packages (from aws-parallelcluster==2.8.0)
Requirement already up-to-date: PyYAML>=5.1.2 in /usr/local/lib64/python3.6/site-packages (from aws-parallelcluster==2.8.0)
Requirement already up-to-date: botocore<1.18.0,>=1.17.53 in /usr/local/lib/python3.6/site-packages (from boto3>=1.14.3->aws-parallelcluster==2.8.0)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.6/site-packages (from boto3>=1.14.3->aws-parallelcluster==2.8.0)
Requirement already up-to-date: s3transfer<0.4.0,>=0.3.0 in /usr/local/lib/python3.6/site-packages (from boto3>=1.14.3->aws-parallelcluster==2.8.0)
Requirement already up-to-date: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.6/site-packages (from botocore<1.18.0,>=1.17.53->boto3>=1.14.3->aws-parallelcluster==2.8.0)
Requirement already up-to-date: docutils<0.16,>=0.10 in /usr/local/lib/python3.6/site-packages (from botocore<1.18.0,>=1.17.53->boto3>=1.14.3->aws-parallelcluster==2.8.0)
Requirement already up-to-date: urllib3<1.26,>=1.20; python_version != "3.4" in /usr/local/lib/python3.6/site-packages (from botocore<1.18.0,>=1.17.53->boto3>=1.14.3->aws-parallelcluster==2.8.0)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.18.0,>=1.17.53->boto3>=1.14.3->aws-parallelcluster==2.8.0)
Installing collected packages: boto3, future, tabulate, aws-parallelcluster
  Running setup.py install for boto3 ... done
  Running setup.py install for future ... done
  Running setup.py install for tabulate ... done
  Running setup.py install for aws-parallelcluster ... done
Successfully installed aws-parallelcluster-2.8.0 boto3-1.14.53 future-0.18.2 tabulate-0.8.3
```
```
AWS-HPC-Quickstart-ResearcherB0ACBDEC-1058NFFMNDDPU:~/environment $ pcluster list --color
Traceback (most recent call last):
  File "/usr/bin/pcluster", line 33, in <module>
    sys.exit(load_entry_point('aws-parallelcluster==2.8.0', 'console_scripts', 'pcluster')())
  File "/usr/bin/pcluster", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for aws-parallelcluster
```

**Comment by rsignell-usgs** [comment]
I was able to install pcluster into my Cloud 9 workspace using conda (installing `aws-parallelcluster=2.8.0` from the conda-forge channel), but when I list, I do not see the new stack.  Only an old stack "habenero2" I created using pcluster 2.6.1 back in May:
![2020-09-02_8-09-22](https://user-images.githubusercontent.com/1872600/91980098-bcaf4580-ecf4-11ea-86e5-17b33df72eec.png)

**Comment by rsignell-usgs** [comment]
Ah, okay, I did `pcluster create hpc-cluster` and (after waiting 5 minutes) I see now:
```
(aws) AWS-HPC-Quickstart-ResearcherB0ACBDEC-1058NFFMNDDPU:~/environment $ pcluster list --color
hpc-cluster  CREATE_COMPLETE  2.8.0
habanero2    CREATE_COMPLETE  2.6.1
```
I'm guessing the No-Tears cloud formation script quit before it created the cluster?

**Comment by sean-smith** [comment]
yup - I'm testing the changes, looks like the pip command we use to install isn't working as desired.
